language: php
php:
# - 5.4
- 5.5
# - 5.6
services:
- cassandra
before_install:
- sudo apt-get update -q
- sudo apt-get install apache2 libapache2-mod-fastcgi 
- printf "\n" | pecl install imagick
# Should also install php5-mcrypt php5-imagick
- /home/travis/.phpenv/versions/5.5/bin/composer self-update
install:
- composer install
before_script:
- cqlsh 127.0.0.1 -f etc/bootstrap.init-keyspace-ci.sql
- cqlsh 127.0.0.1 -f etc/bootstrap.sql
- cqlsh 127.0.0.1 -f etc/ci/testdata.sql
- sudo ln -s ../../../etc/ci/simplesamlphp-metadata vendor/andreassolberg/simplesamlphp/metadata
- sudo ln -s ../../../etc/ci/simplesamlphp-config vendor/andreassolberg/simplesamlphp/config
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
# Not permissions to do that....
# - sudo cat etc/ci/php-fpm.conf >> ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
- sudo a2enmod rewrite actions fastcgi alias env
- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "display_errors = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
- sudo cp -f etc/ci/apache.conf /etc/apache2/sites-available/default
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
- mkdir logs
- sudo service apache2 restart
script:
#- phpunit --debug -v --coverage-clover build/logs/clover.xml --bootstrap lib/_autoload.php tests
# - phpunit --debug -v --bootstrap lib/_autoload.php tests/OAuth.php
- bin/feideconnect.php users
- phantomjs tests-phantomjs/main.js
# Run PHPinfo
# - curl http://127.0.0.1/phpinfo
- cat logs/error.log
- cat logs/access.log
# notifications:
#   slack: uninett:5CpnkrlaqOLKLXDttDzpTqqU
# addons:
#   code_climate:
#     repo_token: 2aad4fd8a7ffbcc2f41f88c69c93c6b0a8abed2c01f14f0f50dc81ef6184e8d8
# after_script:
# - CODECLIMATE_REPO_TOKEN="2aad4fd8a7ffbcc2f41f88c69c93c6b0a8abed2c01f14f0f50dc81ef6184e8d8" vendor/bin/test-reporter --stdout > codeclimate.json
# - 'curl --verbose -X POST -d @codeclimate.json -H ''Content-Type: application/json'' -H ''User-Agent: Code Climate (PHP Test Reporter v0.1.1)'' https://codeclimate.com/test_reports'
cache:
  apt: true
  directories:
  - node_modules
  - vendor
env:
  global:
    # Feide test account
    secure: bJxhb7e5coyY4YgyAsjSB3ewvOLA+KLDrVMl+lGh155IOFDhYdI34YI2g6B3sFesXq4ewySXfMEaJGo1GJcKOIkrYfntvQZ/2LHiZLMpfaFNx/kiUfFLslapbHM90afktWbyNbzK46BmOpBAvM9T7V8tolwRrBgS/U9uG+k0A0s=
