language: php
php:
# - 5.4
- 5.5
# - 5.6
services:
- cassandra
before_install:
- sudo apt-get update -q
install:
- composer install
before_script:
- cqlsh 127.0.0.1 -f etc/bootstrap.init-keyspace-ci.sql
- cqlsh 127.0.0.1 -f etc/bootstrap.sql
- cqlsh 127.0.0.1 -f etc/ci/testdata.sql
script:
- bin/cassa2.php
- bin/cassa1b.php
- bin/cassa1.php



